### ISSUE TITLE
Faiss index

### ISSUE THREAD

**Issue by FYYFU** [florin-git/The-Power-of-Noise#1]
Hi, 
 Thanks for your awesome paper and code. I noticed that the generated index cannot be found in both the repo and google drive. And there is also no instruction on how to create the index from scratch.
 Could you please share the process to create the index or share the index through google drive?

Thanks,

**Comment by florin-git** [comment]
Hi,
Thank you very much for expressing your interest in our paper.

Regarding the index data, due to their substantial size (over 40 GB), we opted not to upload them directly. However, I'm more than happy to guide you through the process of generating this index from scratch using our provided code:

## Initialization and Embedding:

Utilize the `retriever.py` script. Begin by initializing a retriever instance (e.g., Contriever) and then apply the `encode_corpus` method to embed each document in the corpus. Given the considerable volume of the data (21M entries), this step is resource-intensive, requiring significant RAM and time. To manage this, the script is designed to save embeddings to disk at regular intervals (`save_every`  steps). This approach allows for the temporary release of memory by re-initializing the embeddings list before loading new data.

## Concatenating Embeddings:

After completing the embedding phase, the next step involves concatenating all the piecewise stored embeddings to form the final corpus embeddings. 

## Indexing with FAISS:

With the embeddings ready, you can move on to indexing using the `index.py`  script. This involves leveraging the `index_data`  method to process the embeddings through FAISS, followed by the `serialize`  method to save the FAISS index on disk.

I hope this detailed guide assists you in generating the index. Should you require further clarification or encounter any issues, please feel free to reach out.
