### ISSUE TITLE
IP_index.faiss

### ISSUE THREAD

**Issue by fionandz** [florin-git/The-Power-of-Noise#2]
Hi,
Thanks for your awesome paper and code.I've been following the guidelines outlined in #1 to generate an IP_index.faiss for corpus. However, I've encountered an issue where the search results obtained using this index differ from those provided in contiver_search_results_at150.pkl.
﻿
Could you kindly share the specific code used to create the IP_index.faiss? I'm keen to understand if there are any discrepancies in the indexing process or parameters that might explain this inconsistency.
Thank you very much for your assistance.

**Comment by florin-git** [comment]
Hi,
Thank you for your interest in our paper and code.
I've now uploaded all the scripts covering the different phases of the retrieval process. Here's a brief overview:

**1. Compute Corpus Embeddings**:
The `compute_corpus_embeddings.py` script computes embeddings in batches, storing them in the `output_dir`.

**2. Index Embeddings**:
The `index_embeddings.py` script concatenates the piecewise stored embeddings and creates the index.
- Single Index: Leave `percentages_for_index_splitting` empty.
- Multiple Indices: Specify splitting percentages to create multiple indices.

**3. Retrieve Top-k Documents**:
The `compute_search_results.py` file retrieves the top-k documents for the given queries using the FAISS index/indices created earlier.

### Explanation of Discrepancies:
Discrepancies in search results are likely due to differences in how indices are created and merged:
- Single vs. Multiple Indices: Using one index produces slightly different rankings compared to using multiple indices. When merging results from multiple indices, the `merge_ip_search_results` function from `index.py` sorts them based on combined scores. This can cause slight shifts in the document order compared to a single index.

In the paper's experiments, we used two indices: one containing the first 14M embeddings and the other with the remaining ones. Even when replicating this setup, there were minor shifts in document positions (e.g., document at position 5 moving to position 6), but the overall set of documents remained consistent.

I hope this explanation clarifies the discrepancies you noticed.
