### ISSUE TITLE
Can not observe the experimental phenomenon reported in the paper

### ISSUE THREAD

**Issue by ChengAnda** [florin-git/The-Power-of-Noise#5]
Hi, thanks for your great work. Your conclusion that "adding irrelevant documents in the right place can improve the effect" is very interesting. So I'm trying to reproduce the experimental phenomenon reported in the paper Table 3 with the following models:

> Retriever: bge-large-en-v1.5
> LLM: llama2-7B-Chat

Here are my results:
dataset | metrics | ori_top5 | inv_top5 | nonsense5 + top5 | nonsense5 + inv_top5
-- | -- | -- | -- | -- | --
nq | em | 0.356 | 0.353 | 0.334 | 0.323
nq | acc | 0.491 | 0.480 | 0.503 | 0.478
nq | f1 | 0.463 | 0.463 | 0.446 | 0.435
triviaqa | em | 0.599 | 0.601 | 0.598 | 0.600
triviaqa | acc | 0.703 | 0.692 | 0.699 | 0.701
triviaqa | f1 | 0.705 | 0.705 | .0700 | 0.704
popqa | em | 0.389 | 0.375 | 0.378 | 0.362
popqa | acc | 0.522 | 0.495 | 0.517 | 0.487
popqa | f1 | 0.471 | 0.450 | 0.456 | 0.434

where "ori_top5" means the ordinary rag with top5 docs, "inv_top5" means using inverse-ordered top5 docs as contexts, "nonsense5" means adding 5 nonsense docs before the retrieved docs.
**As shown in the above table, while using top5 docs, the ordinary ori_top5 setting performs best on all datasets.**

But when I experimented on top1, I could observe experimental phenomena consistent with those in the paper on some datasets (triviaqa and popqa).

dataset | metrics | ori_top1 | nonsense5 + top1
-- | -- | -- | --
nq | em | 0.329 | 0.307
nq | acc | 0.417 | 0.409
nq | f1 | 0.421 | 0.400
triviaqa | em | 0.556 | 0.569
triviaqa |acc | 0.625 | 0.637
triviaqa |f1 | 0.643 | 0.657
popqa | em | 0.362 | 0.373
popqa | acc | 0.456 | 0.461
popqa | f1 | 0.431 | 0.438

Do you have any ideas about these results? 
Have you conducted experiments on different datasets and different retriever models?

**Comment by florin-git** [comment]
Hi,
Thank you very much for your interest in our paper and for sharing these experimental results.

The differences in results can be primarily attributed to your choice of retriever. BGE is a more powerful model than the Contriever we used in our experiments, which is evident from your higher baseline accuracy scores (~50% vs our 20-25%). This performance gap is likely due to BGE's extensive training, which included exposure to datasets like NQ and TriviaQA. As a result, BGE is already highly effective at retrieving relevant documents, limiting any potential improvements from the addition of random documents.
